### ISSUE TITLE
Admission webhook url 

### ISSUE THREAD

**Issue by sebastianpena** [circa10a/k8s-label-rules-webhook#15]
What should be the value of the URL for clientConfig?
I pointed it to the NodePort exposed by the service, but fails as it expects an HTTPS response.

  clientConfig:
    url: "https://<deployed-app-location>/"

Error from server (InternalError): error when creating "test.yaml": Internal error occurred: failed calling webhook "my.application.domain": Post https://x.x.x.x:31422/?timeout=30s: http: server gave HTTP response to HTTPS client

**Comment by circa10a** [comment]
@sebastianpena All admissions webhooks are expected to be served over https. You can generate your own cabundle to do this. [Similar GitHub issue](https://github.com/kubernetes/kubernetes/issues/61171)

- [Docs to serve webhook via service reference](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#service-reference)
- [Docs to contact webhook outside of the cluster](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#url)

**Comment by sebastianpena** [comment]
Thanks for the reply @circa10a. 
Im a bit confused. Does your server (label-rules-webhook) provide https or are you expecting something else to provide it. Like the ingress controller.

**Comment by circa10a** [comment]
@sebastianpena something else should provide it. That could be an ingress controller, maybe a paas like heroku.
[Caddy server](https://caddyserver.com/) providers automatic https via let's encrypt, so you could use that as a reverse proxy.

**Comment by sebastianpena** [comment]
Thanks @circa10a. Have you tried running it via a service with a self signed certificate?
Any instructions would be great.
In this example the ssl cert is in the webhook itself.
https://github.com/kubernetes/kubernetes/issues/61171

**Comment by tlkamp** [comment]
@sebastianpena you can generate a certificate and submit a signing request to the cluster CA. Once signed, store the files as k8s secrets and mount them somewhere in your container's filesystem.

**Comment by circa10a** [comment]
@sebastianpena Hopefully [this](https://github.com/circa10a/k8s-label-rules-webhook/blob/master/README.md#deploy-webhook-application-tls) is what you were looking for.

**Comment by sebastianpena** [comment]
Awesome work @circa10a !!! 
That's exactly what I was looking for.
Thanks for all the quick responses and nice code.

**Comment by circa10a** [comment]
@sebastianpena if this resolves your question/problem. Please remember to close the issue.

**Comment by sebastianpena** [comment]
Question answered. 
Thank you.

**Comment by hmike96** [comment]
If we generate our own certificate and place it in the application like in the example, but also are hosting the deployment in cluster, do you have to set the caBundle argument in the webhook configuration resource with the cert provided in the configmap? @circa10a

**Comment by circa10a** [comment]
@hmike96 

There are 2 options.

- Provide the ca bundle in the webhook config. [See TLS section](https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/)
- Or create a [cert signing request](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificate-signing-request-object-to-send-to-the-kubernetes-api) to have the cluster trust the certificate.
