### ISSUE TITLE
Writing medium article 

### ISSUE THREAD

**Issue by hmike96** [circa10a/k8s-label-rules-webhook#27]
Hi @circa10a 

I am writing a medium article on my companies medium platform on using cert manager for internal PKI. I was wondering if I could use your webhook here in my example when i demonstrate using a cert-manager internal CA authority to provision a TLS certificate. I will clearly cite your work giving you credit. Thanks!

**Comment by circa10a** [comment]
@hmike96 Absolutely!
The project is MIT licensed, therefore you can do anything that you want with it 😄
